apiVersion: v1
kind: ReplicationController
metadata:
  name: revive-adserver
  labels:
    name: revive-adserver
spec:
  replicas: 1
  selector:
    name: revive-adserver
  template:
    metadata:
      labels:
        name: revive-adserver
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: php-fpm
          image: zvelo/revive-adserver-php-fpm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SMTP_SERVER
              value: <SMTP_SERVER>:<SMTP_PORT>
            - name: SMTP_USER
              value: <SMTP_USER>
            - name: SMTP_PASS
              value: <SMTP_PASS>
            - name: SMTP_TLS
              value: "yes"
          volumeMounts:
            - mountPath: /data
              name: data
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: nginx
          image: zvelo/revive-adserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
