apiVersion: v1
kind: ReplicationController
metadata:
  name: revive-adserver
  labels:
    name: revive-adserver
spec:
  replicas: 1
  selector:
    name: revive-adserver
  template:
    metadata:
      labels:
        name: revive-adserver
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: php-fpm
          image: zvelo/revive-adserver-php-fpm
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/var
              name: var
            - mountPath: /var/www/plugins
              name: plugins
            - mountPath: /var/www/www/admin/plugins
              name: adminplugins
            - mountPath: /var/www/www/images
              name: images
        - name: nginx
          image: zvelo/revive-adserver
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: var
          emptyDir: {}
        - name: plugins
          emptyDir: {}
        - name: adminplugins
          emptyDir: {}
        - name: images
          emptyDir: {}
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
