apiVersion: v1
kind: Service
metadata:
  name: revive-adserver
  labels:
    name: revive-adserver
spec:
  selector:
    name: revive-adserver
  ports:
  - port: 80
    name: http
    nodePort: 31313
  - port: 443
    name: https
    nodePort: 31315
